.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SM 1 "June 14, 2007"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sm \- Displays a short text fullscreen
.SH SYNOPSIS
.B sm
.RI [ text | -  ]
.SH DESCRIPTION
.BR Screen\ Message 
will display a given multi-line message as large as
possible, fullscreen and black on white. You can specify the text either
when launching sm, or edit it while the program is running.
.PP
To clear the displayed text, press Escape.
.PP
To quit the program, press Ctrl-Q or press the button.
.br

.SH OPTIONS
.TP
.RI [ text ]
Text to display at start up. Defaults to ":-)". If "-" is passed to sm,
it will read the text to display from stdin.

.SH AUTHOR
This manual page was written by Joachim Breitner <mail@joachim-breitner.de>.
