.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH SM 6 "November 24, 2012"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
sm \- Displays a short text fullscreen
.SH SYNOPSIS
.B sm
[ OPTIONS ]
[
.I text
|
.B \-
]
.SH DESCRIPTION
.BR Screen\ Message 
will display a given multi-line message as large as
possible, fullscreen and black on white. You can specify the text either
when launching sm, or edit it while the program is running.
.PP
After a short timeout, the text entry and the quit button will disappear, leaving
nothing on the screen but the entered text. To continue entering text, just start
typing or (left-)click anywhere on the screen.
.PP
To clear the displayed text, press Escape.
.PP
To invert the colors of the text and the background, press Ctrl-I.
.PP
To quit the program, press Ctrl-Q, or Escape twice, or click the "Quit"-button.
.br

.SH OPTIONS
.TP
[ \fItext\fR | \fB\-\fR ]
Text to display at start up. Defaults to ":-)". If "\fB\-\fR" is passed to sm,
it will read the text to display from the standard input, see \fBREMOTE CONTROLLING SM\fR.
.TP
.BI \-f,\ \-\-foreground= colordesc
Define a different color to use for the foreground of the text to
display than black. The text string can be in any of the forms accepted
by XParseColor; these include name for a color from rgb.txt, such as
DarkSlateGray, or a hex specification such as #3050b2 or #35b.
.TP
.BI \-b,\ \-\-background= colordesc
Define a different color to use for the background of the text to
display than white. For possible values, see above.
.TP
.BI \-i,\ \-\-invert
Switch the roles for foreground and background colors. Useful if you prefer
white-on-black.
.TP
.BI \-n,\ \-\-font= fontspec
Define a different font to use than the default sans-serif font of your
system. The fontspec be the complete name for a truetype font (like
"DejaVu Sans" or "Bitstream Vera Serif") or just a short font family
specification ("serif", "sans-serif").
.TP
.BI \-r,\ \-\-rotate= rotation
Rotates the display by rotation*90 degrees counter-clock-wise. So \-r 1 
rotates the display to the left, and \-r 2 puts it upside down.
.TP
.BI \-a,\ \-\-align= alignment
Aligns the text centered (\-a 0), left (\-a 1) or right (\-a 2).
.TP
.BI \-\-
(Double dash) End option parsing. This is used to be able to actually hand over text
that starts of with an dash.
.TP
.BI \-h,\ \-\-help
This option will give you a short usage message summarizing the
recognized options and quits.
.TP
.BI \-V,\ \-\-version
This prints the project name together with its version number
quits.

.SH REMOTE CONTROLLING SM
If sm is called with \fB\-\fR as a command line argument, it will read the text to be
shown from the standard input. It will read the input until it reaches the end
of the file, or the form feed character \fB\\f\fR, and show the input read so far at
once. Newline characters at the beginning or the end are ignored. The input is assumed to be UTF-8 encoded 
.RB "(see " utf8 (7)).
.PP
This can be used to create automatic displays of changing data or similar tricks. For example, the following command will create a simple digital watch:
.sp
.B (while sleep 1; do date +%T; printf '\\\\f'; done) | sm -


.SH AUTHOR
This manual page was written by Joachim Breitner
<mail@joachim-breitner.de> and updated by Gerfried Fuchs <rhonda@deb.at>
to reflect additions for commandline option handling.
